# Generated by Django 3.2.14 on 2022-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
