# Generated by Django 3.2.14 on 2022-07-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
