# Generated by Django 3.2.14 on 2022-07-18 09:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
