# Generated by Django 3.2.14 on 2022-07-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('-id',), 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
    ]
