# Generated by Django 3.2.14 on 2022-07-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
            },
        ),
        migrations.RemoveField(
            model_name='footer',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_link',
        ),
        migrations.AddField(
            model_name='footer',
            name='website_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='social',
            field=models.ManyToManyField(blank=True, null=True, to='footer.Social'),
        ),
    ]
