# Generated by Django 3.2.14 on 2022-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_auto_20220718_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
