# Generated by Django 3.2.14 on 2022-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_remove_footer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='social',
            field=models.ManyToManyField(blank=True, to='footer.Social'),
        ),
    ]
