# Generated by Django 3.2.14 on 2022-07-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0005_alter_footer_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ('-id',), 'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
    ]
