# Generated by Django 4.0.6 on 2022-07-20 14:54

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0006_alter_footer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='privacy_policy',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
