# Generated by Django 3.2.14 on 2022-07-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ('-id',), 'verbose_name': 'Hero', 'verbose_name_plural': 'Hero'},
        ),
    ]
